version: 1

formatters:
    syslog_fmt:
        format: '%(name)s: [%(request)s] %(message)s'

filters:
    context:
        (): synapse.logging.context.LoggingContextFilter
        request: ""

handlers:
    syslog:
        class: logging.handlers.SysLogHandler
        formatter: syslog_fmt
        filters: [context]
        address: /run/synapse-client_reader-log

root:
    level: INFO
    handlers: [syslog]

disable_existing_loggers: False
